models:
  - hf: Qwen/Qwen2-7B-Instruct
  - hf: mistralai/Mistral-7B-Instruct-v0.3
  - hf: meta-llama/Meta-Llama-3-8B-Instruct

quant: [float16, bnb-int8, bnb-nf4, gptq-int4, awq-int4, gguf-q4]
runtime: [transformers, vllm, llamacpp, exllamav2]
attn_impl: [sdpa, flash_attn_2, eager]
kv_cache: [full, paged]
kv_dtype: [fp16, kv8bit]
batch_size: [1, 4]
seed: 42
max_tokens: 256

presets:
  - name: chat_only
    prompts: [chara_shopping_dialog, chara_charming_dialog, chara_drilling_dialog, chara_sad_dialog, chara_social_rule_dialog]

repeats: 3  # warmup1 + 本計測2

